### ISSUE TITLE
RStudio by tags

### ISSUE THREAD

**Issue by latot** [jgenco/jgenco-overlay#9] opened 2023-03-14 15:26 UTC
Hi!, thx for bringing RStudio alive again!

I was thinking, just avoid use the 9999 versions, its great for live abuilds, but in a package manager like portage, I think is even greater use for example the github tags. and with that, we would be able to upgrade the versions (with 9999 portage can't know when there is a new version).

I in the past, created alot of 9999 versions, but after some time, there was this type of problems, hard to know when builds, when not, what patches are needed only for some verions..., well git tags helps with all that :)

https://leo3418.github.io/2023/02/07/avoid-9999-only-gentoo-packages.html

Thx!

**Comment by jgenco** [comment] 2023-03-15 18:33
I generally use the 9999 versions for development of the next version.   The problem is upstream does not have a lot of releases/[tags](https://github.com/rstudio/rstudio/tags).  They release a new branch(flower) about once a quarter and one or two patches for previous branches.  I guess you would like to see is something closer to [RSudio dailies](https://dailies.rstudio.com/).  If this is the case I'm curious which branch(or both) should be available.  
[Curently](https://dailies.rstudio.com/rstudio/) they have:
- 2022.12.1 - [elsbeth-geranium](https://github.com/rstudio/rstudio/tree/elsbeth-geranium) - This will be the next small patch
- 2023.03.0 - [cherry-blossom](https://github.com/rstudio/rstudio/tree/rel-cherry-blossom) - next version
- 2023.05.0 - [Mountain Hydrangea](https://github.com/rstudio/rstudio/tree/main) - the current 9999 build

The last question would be at what rate should I update new versions?

One problem that would be that almost all packages in this repo are ~amd64, though I was thinking of fixing that around April.  While thinking about this response, I  realized I could simply mask these versions instead.

While you didn't mention Quarto-Cli, they have a new pre-release versions between every couple of days to a dozen a day.  I think a pre-release version would be good for it, but I put it off because of the ~amd64 problem above.

**Comment by latot** [comment] 2023-03-15 19:10
Is hard to says at what rate....

But if there is too low tags, is possible chose a commit, and use a version number that is lower (more dicimals) than the tags.

The best would be, custom tag, follow the RStudio nomenclature

vYear.month.day+number

Would not be an official tag but helps to sort everything.

In the of Quarto, I really would like a way to auto-generate that ebuilds, Quarto is not the only one. I don't know if there is a way to configure github to know when there is a new version, and only if fails know it (? (I'm dreaming)

You could think of 1 time at week (? seems enough at least for me, for gentoo, daily releases is not great, unless there is a critical bug. Except if the package is the bin type.

**Comment by jgenco** [comment] 2023-03-17 20:53
I added a package.mask for Quarto-Cli and RStudio.  I'll wait until the weekend to a add a Quarto-Cli-1.3.x version in case something went wrong.

As a new Rstudio version was just released I will be testing various USE flags.   I won't get around to adding a non 9999 ebuild of 2023.05.0(Mountain Hydrangea) for about a week.  I think fortnightly might be a better pace for Rstudio as sometimes they don't commit for days but time will tell.

RStudio's version format now uses a known algorithm instead of a pseudo-random ever increasing number. It is based on the number of commits after a [base commit](https://github.com/rstudio/rstudio/blob/724552865da880f6a40af50b9507de3bf0403433/version/base_commit/).  See [rstudio-version.sh](https://github.com/rstudio/rstudio/blob/724552865da880f6a40af50b9507de3bf0403433/docker/jenkins/rstudio-version.sh)

While I've never used it, I would look into [GitHub Actions](https://docs.github.com/en/actions) to auto update ebuilds.   You could have it check one of the following places 
 + [_prerelease.json](https://quarto.org/docs/download/_prerelease.json)
+ [_download.json](https://quarto.org/docs/download/_download.json)
+ [releases](https://api.github.com/repos/quarto-dev/quarto-cli/releases)

 depending on what you want and how often, and update the ebuild as needed.  Assuming nothing changed upstream you would only have to change the filename and update the Manifest which could be done in bash.  Also there are some actions in the [Github Marketplace](https://github.com/marketplace?query=gentoo) that relate to Gentoo ebuilds/overlays.

**Comment by jgenco** [comment] 2023-03-31 01:47
With rstudio-2023.05.0.92, I now have per-release versions of both the 9999 builds.  You are welcome to try it.

**Comment by latot** [comment] 2023-03-31 02:19
I'll try tomorrow :)

**Comment by jgenco** [comment] 2023-05-28 19:47
While latot apparently died :), I did change how RStudio is built last week in 5a99ec5fb76fdd17f18e0c54911934ba559e2ad3.

Inspired by [peeweep/gentoo-go-deps](https://github.com/peeweep/gentoo-go-deps), this uses prebuilt `node_modules` built by a [GitHub Action](https://github.com/jgenco/jgenco-overlay-files/blob/main/.github/workflows/rstudio.yml) for both Panmirror and Electron builds.  This allows both to be patched (if needed/wanted) and built from source instead of relying on prebuilt files by RStudio.  This is the same way [Fedora](https://src.fedoraproject.org/rpms/rstudio) does it.  Except, I used GitHub Action to build the `node_modules` as it seemed more transparent in my case.

So any feedback or build problems would be appreciated.

**Comment by latot** [comment] 2023-05-28 21:32
Sorry! I forgot it u.u

But I have been updateting RStudio without problems :) Thx!

**Comment by jgenco** [comment] 2023-07-17 02:46
I should have closed this when I finished it, but there was a big change (unrelated to this issue) at the same time and I was curious if there were any problems.  There seems to be none. 

I have come to think having non-live *and* live ebuilds are better than just live ebuilds.

I also discovered another reason to do them.  Sometimes upstream build systems rely on git.  This causes non git/live ebuilds to fail.

**Closed by jgenco** 2023-07-17 02:46 UTC
